import Head from "next/head";

import { Layout } from "../components/shared";

const Home = () => {
	return (
		<div>
			<Head>
				<title>AfriSend</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

      <main>
				Afrisend Money Transfer App
			</main>

		</div>
	);
}

Home.getLayout = function getLayout(page) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}

export default Home;